version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/BE"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/FE"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
